version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mssql-init:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      - DBHOST=mssql
      - DBPORT=1433
    networks:
      - go-net

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/localhost/1433'"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - go-net

  mssql-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      mssql:
        condition: service_healthy
    volumes:
      - ./mssql-init:/scripts
    entrypoint: ["/bin/bash", "-c", "sleep 10 && /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P YourStrong@Passw0rd -i /scripts/init.sql"]
    networks:
      - go-net
    restart: "no"

networks:
  go-net:
